// Generated by https://quicktype.io

export interface PlacesResponse {
  type:        string;
  query:       string[];
  features:    Feature[];
  attribution: string;
}

export interface Feature {
  id:                   string;
  type:                 string;
  place_type:           string[];
  relevance:            number;
  properties:           Properties;
  text_es:              string;
  language_es?:         Language;
  place_name_es:        string;
  text:                 string;
  language?:            Language;
  place_name:           string;
  center:               number[];
  geometry:             Geometry;
  context:              Context[];
  matching_text?:       string;
  matching_place_name?: string;
}

export interface Context {
  id:          ID;
  mapbox_id:   MapboxID;
  wikidata:    Wikidata;
  text_es:     Text;
  language_es: Language;
  text:        Text;
  language:    Language;
  short_code?: ShortCode;
}

export enum ID {
  Country8734 = "country.8734",
  Place1304606 = "place.1304606",
  Region74782 = "region.74782",
}

export enum Language {
  Es = "es",
}

export enum MapboxID {
  DXJuOm1IeHBsYzpBU1FL = "dXJuOm1ieHBsYzpBU1Fl",
  DXJuOm1IeHBsYzpFK2DL = "dXJuOm1ieHBsYzpFK2dl",
  DXJuOm1IeHBsYzpJaDQ = "dXJuOm1ieHBsYzpJaDQ",
}

export enum ShortCode {
  Bo = "bo",
  BoL = "BO-L",
}

export enum Text {
  Bolivia = "Bolivia",
  DepartamentoDeLaPaz = "Departamento de La Paz",
  NuestraSeñoraDeLaPaz = "Nuestra Señora de La Paz",
}

export enum Wikidata {
  Q1491 = "Q1491",
  Q272784 = "Q272784",
  Q750 = "Q750",
}

export interface Geometry {
  coordinates: number[];
  type:        string;
}

export interface Properties {
  wikidata?:  string;
  landmark:   boolean;
  address?:   string;
  foursquare: string;
  category:   string;
  maki?:      string;
}
